#!/usr/bin/env python3
"""Regenerate include/cthtml/entities.hpp.

The data is the WHATWG named character reference table
(https://html.spec.whatwg.org/multipage/named-characters.html), taken
from CPython's html.entities.html5 mapping so regeneration needs no
network. cthtml requires the terminating semicolon, so the legacy
no-semicolon forms are skipped; every kept reference decodes to one or
two code points, sorted by name (byte order) for binary search.

Usage:  python3 tools/gen-entities.py
"""

from html.entities import html5
from pathlib import Path

HEADER = """\
#ifndef CTHTML__ENTITIES__HPP
#define CTHTML__ENTITIES__HPP

#include "../ctll/fixed_string.hpp"
#ifndef CTHTML_IN_A_MODULE
#include <cstddef>
#include <string_view>
#endif

// The WHATWG named character reference table ({count} names, the
// semicolon-terminated forms), GENERATED by tools/gen-entities.py - do
// not edit by hand. Entries are sorted by name (byte order, names are
// case-SENSITIVE: &Uuml; and &uuml; differ) so lookup is a binary
// search; a reference may decode to one or two code points (second ==
// 0 means one).

namespace cthtml::detail {{

struct entity_ref {{
	std::string_view name;
	char32_t first;
	char32_t second;
}};

inline constexpr entity_ref entity_table[] = {{
{rows}
}};

constexpr const entity_ref * find_entity(std::string_view name) noexcept {{
	size_t lo = 0;
	size_t hi = sizeof(entity_table) / sizeof(entity_table[0]);
	while (lo < hi) {{
		const size_t mid = lo + (hi - lo) / 2;
		if (entity_table[mid].name < name) {{
			lo = mid + 1;
		}} else if (name < entity_table[mid].name) {{
			hi = mid;
		}} else {{
			return &entity_table[mid];
		}}
	}}
	return nullptr;
}}

}} // namespace cthtml::detail

#endif
"""


def main() -> None:
    refs: dict[str, list[int]] = {}
    for name, chars in html5.items():
        if not name.endswith(";"):
            continue
        cps = [ord(c) for c in chars]
        assert 1 <= len(cps) <= 2, (name, cps)
        refs[name[:-1]] = cps

    rows = []
    for name in sorted(refs):
        first, *rest = refs[name]
        second = rest[0] if rest else 0
        rows.append(f'    {{"{name}", 0x{first:X}, 0x{second:X}}},')

    out = Path(__file__).resolve().parent.parent / "include" / "cthtml" / "entities.hpp"
    out.write_text(HEADER.format(count=len(refs), rows="\n".join(rows)))
    print(f"wrote {out} ({len(refs)} references)")


if __name__ == "__main__":
    main()
